# Generated by Django 3.2 on 2021-04-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='address',
            field=models.CharField(max_length=700),
        ),
    ]
